#!/usr/bin/env node

/**
 * import-data.mjs
 * ---------------
 * Converts a JSON export from the Vercel/Prisma system into SQL INSERT
 * statements for the Cloudflare D1/Drizzle database.
 *
 * Usage:
 *   node scripts/import-data.mjs export.json > import.sql
 *   wrangler d1 execute ttv-database --local --file=import.sql
 *   wrangler d1 execute ttv-database --remote --file=import.sql
 */

import { readFileSync } from "node:fs";

const inputPath = process.argv[2];
if (!inputPath) {
  console.error("Usage: node scripts/import-data.mjs <export.json>");
  process.exit(1);
}

const data = JSON.parse(readFileSync(inputPath, "utf-8"));

// ── helpers ──────────────────────────────────────────────────────────────

/** Escape single quotes for SQLite string literals. */
function esc(str) {
  if (str == null) return "NULL";
  return `'${String(str).replace(/'/g, "''")}'`;
}

/** Convert an ISO timestamp string to unix seconds, or NULL. */
function ts(value) {
  if (value == null) return "NULL";
  return Math.floor(new Date(value).getTime() / 1000);
}

/** Convert emailVerified (DateTime | null) to integer boolean (1 | 0). */
function boolInt(value) {
  return value ? 1 : 0;
}

// ── SQL generation ───────────────────────────────────────────────────────

const lines = [];

lines.push("-- Generated by import-data.mjs");
lines.push(`-- Source exported at: ${data.exportedAt}`);
lines.push("");

// 1. user (no FK deps)
for (const u of data.users ?? []) {
  lines.push(
    `INSERT OR IGNORE INTO \`user\` (id, name, email, emailVerified, image) VALUES (${esc(u.id)}, ${esc(u.name ?? "")}, ${esc(u.email)}, ${boolInt(u.emailVerified)}, ${u.image != null ? esc(u.image) : "NULL"});`,
  );
}
lines.push("");

// 2. Roles (no FK deps)
for (const r of data.roles ?? []) {
  lines.push(
    `INSERT OR IGNORE INTO \`Roles\` (id, name, createdAt, updatedAt) VALUES (${esc(r.id)}, ${esc(r.name)}, ${ts(r.createdAt)}, ${ts(r.updatedAt)});`,
  );
}
lines.push("");

// 3. curriculum (no FK deps)
for (const c of data.curricula ?? []) {
  lines.push(
    `INSERT OR IGNORE INTO \`curriculum\` (id, title, description, createdAt, updatedAt) VALUES (${esc(c.id)}, ${esc(c.title)}, ${esc(c.description ?? "")}, ${ts(c.createdAt)}, ${ts(c.updatedAt)});`,
  );
}
lines.push("");

// 4. programPartner (no FK deps)
for (const p of data.programPartners ?? []) {
  lines.push(
    `INSERT OR IGNORE INTO \`programPartner\` (id, name, createdAt, updatedAt) VALUES (${esc(p.id)}, ${esc(p.name)}, ${ts(p.createdAt)}, ${ts(p.updatedAt)});`,
  );
}
lines.push("");

// 5. UserRoles (depends on user + Roles)
for (const ur of data.userRoles ?? []) {
  lines.push(
    `INSERT OR IGNORE INTO \`UserRoles\` (id, userId, roleId, createdAt, updatedAt) VALUES (${esc(ur.id)}, ${esc(ur.userId)}, ${esc(ur.roleId)}, ${ts(ur.createdAt)}, ${ts(ur.updatedAt)});`,
  );
}
lines.push("");

// 6. program (depends on curriculum)
for (const p of data.programs ?? []) {
  lines.push(
    `INSERT OR IGNORE INTO \`program\` (id, name, description, curriculumId, startDate, endDate, createdAt, updatedAt) VALUES (${esc(p.id)}, ${esc(p.name)}, ${esc(p.description ?? "")}, ${esc(p.curriculumId)}, ${ts(p.startDate)}, ${ts(p.endDate)}, ${ts(p.createdAt)}, ${ts(p.updatedAt)});`,
  );
}
lines.push("");

// 7. programRole (depends on program + user)
for (const pr of data.programRoles ?? []) {
  lines.push(
    `INSERT OR IGNORE INTO \`programRole\` (id, programId, userId, name, createdAt, updatedAt) VALUES (${esc(pr.id)}, ${esc(pr.programId)}, ${esc(pr.userId)}, ${esc(pr.name)}, ${ts(pr.createdAt)}, ${ts(pr.updatedAt)});`,
  );
}
lines.push("");

// 8. programApplication (depends on user + program + programPartner)
for (const pa of data.programApplications ?? []) {
  const appJson =
    typeof pa.application === "string"
      ? pa.application
      : JSON.stringify(pa.application);
  lines.push(
    `INSERT OR IGNORE INTO \`programApplication\` (id, programId, userId, partnerId, status, application, completedAt, createdAt, updatedAt) VALUES (${esc(pa.id)}, ${pa.programId != null ? esc(pa.programId) : "NULL"}, ${esc(pa.userId)}, ${pa.partnerId != null ? esc(pa.partnerId) : "NULL"}, ${esc(pa.status)}, ${esc(appJson)}, ${ts(pa.completedAt)}, ${ts(pa.createdAt)}, ${ts(pa.updatedAt)});`,
  );
}
lines.push("");

process.stdout.write(lines.join("\n") + "\n");
